### ISSUE TITLE
Live Server = barrier

### ISSUE THREAD

**Issue by dafhi** [erichlof/THREE.js-PathTracing-Renderer#49]
I miss the days of dragging index.html into firefox.  Pressing F5 in a browser after editing via Notepad++ isn't that big of a deal.  I realize three.js might have made the switch and THREE.js PathTracing Renderer is being 'compliant' but it's a barrier to adoption

**Comment by erichlof** [comment]
@dafhi 
Yes, development for the web has changed a lot over the past few years even. As long as you're not loading textures, sounds, or models into your work, I believe you can still get away with not having a server running in the background. But due to security concerns (not so much for me and my use cases), if you try to pull anything off 'disk' , you have to pull it off of a served page, which is annoying if you're just developing on your own machine at home. -Edit: now that I think about it,  I believe you might need a served page for even a bare bones demo without any textures or images because the glsl shaders have to be pulled in and compiled, but I could be mistaken about that particular case. -

I will say this though: Microsoft's Visual Studio Code (a free code editor) has broken down some of these barriers with its Live Server plugin. It is very transparent, I hardly even notice anymore that it has to start up when I start Visual Studio Code for once during an entire day. I just leave it running in the background,  even if I'm not coding at the moment and watching YouTube instead of working (lol). I just fire up the editor,  click a button to start the server and then when I make changes to the code, it will automatically refresh the page, so I don't even have to click Run or F5 or anything. And although it seems like a small matter,  those 'Run' clicks and F5s used to really add up and take their toll on my wrists and fingers, considering I might make hundreds of small changes in 1 development session. This was especially bad when I was programming C, where you are kind of forced to do the dance every time you make a change. 

So I agree with you that I miss the environment of just having everything at my immediate disposal on 1 machine without being connected to the internet.  But if I am doing any kind of Webgl stuff like with this project,  I now prefer (even like) to use Visual Studio Code with the automatic live refresh.

**Comment by dafhi** [comment]
You soiled my original argument.  Brackets is another Live editor that loads much quicker, but .. I reinstalled Win a bit ago and now neither work.

Boo.  Hoo.  If I really wanted to learn JS I guess I would do it

**Comment by erichlof** [comment]
Ha ha, sorry to soil your argument ;-)
I have heard of Brackets but have never tried it - might give it whirl in the near future.  If nothing is working that you have to install, then there are a couple of online only editors for specifically doing JS and web development.  2 of the most popular that come to mind are [Codepen](https://codepen.io/) and [JSFiddle](https://jsfiddle.net/)
These would let you get up and running and allow you to experiment with the language - both update instantly if you check the refresh-on-change box.
Good luck - I hope you are able to solve the new Win install issues!

**Comment by dafhi** [comment]
I do have some outstanding JS samples including older "offline" three js with examples that .. i recall one of them working with new 'three'

I've found my way to 'C' and SDL2.  I will be working with that for a while!  I will be back, I'm sure
